-- =============================================================
-- V1: crear tabla de preguntas
-- Sintaxis portable: PostgreSQL 10+ y H2 (modo PostgreSQL) soportan
-- GENERATED BY DEFAULT AS IDENTITY, BOOLEAN, VARCHAR y CHAR.
-- =============================================================

CREATE TABLE questions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category       VARCHAR(100) NOT NULL,
    question       VARCHAR(1000) NOT NULL,
    option_a       VARCHAR(255) NOT NULL,
    option_b       VARCHAR(255) NOT NULL,
    option_c       VARCHAR(255) NOT NULL,
    option_d       VARCHAR(255) NOT NULL,
    correct_option CHAR(1) NOT NULL,
    difficulty     VARCHAR(20) NOT NULL,
    active         BOOLEAN NOT NULL DEFAULT TRUE
);

-- Índice para consultas por categoría + estado activo
CREATE INDEX idx_questions_category_active ON questions (category, active);
