-- =============================================================
-- V3: ampliar el banco a 10 preguntas por categoría (80 en total).
-- correct_option guarda la letra de la opción correcta (A-D).
-- El backend NUNCA envía correct_option al navegador.
-- Dificultad EASY y activas, igual que V2.
-- =============================================================

INSERT INTO questions
    (category, question, option_a, option_b, option_c, option_d, correct_option, difficulty, active)
VALUES

-- ---------------- FÚTBOL (9 nuevas + 1 de V2 = 10) ----------------
    ('FÚTBOL', '¿Cuánto dura un partido de fútbol profesional sin contar el descanso?',
     '90 minutos', '60 minutos', '120 minutos', '45 minutos', 'A', 'EASY', TRUE),
    ('FÚTBOL', '¿Qué selección ganó el Mundial de Fútbol de 2022?',
     'Brasil', 'Argentina', 'Francia', 'Alemania', 'B', 'EASY', TRUE),
    ('FÚTBOL', '¿Cuántos puntos vale un gol en un partido de fútbol?',
     '1 punto', '2 puntos', '3 puntos', '5 puntos', 'A', 'EASY', TRUE),
    ('FÚTBOL', '¿Qué tarjeta muestra el árbitro para expulsar a un jugador?',
     'Amarilla', 'Azul', 'Roja', 'Verde', 'C', 'EASY', TRUE),
    ('FÚTBOL', '¿Qué jugador es conocido como "la Pulga"?',
     'Cristiano Ronaldo', 'Neymar', 'Kylian Mbappé', 'Lionel Messi', 'D', 'EASY', TRUE),
    ('FÚTBOL', '¿Qué parte del cuerpo NO pueden usar los jugadores para jugar el balón (salvo el portero en su área)?',
     'La cabeza', 'Las manos', 'El pecho', 'Los pies', 'B', 'EASY', TRUE),
    ('FÚTBOL', '¿Cómo se llama la sanción cuando un jugador comete una falta grave dentro del área?',
     'Penal', 'Córner', 'Saque de banda', 'Tiro de esquina', 'A', 'EASY', TRUE),
    ('FÚTBOL', '¿Qué países organizarán juntos el Mundial de Fútbol de 2026?',
     'Brasil y Argentina', 'Qatar y Arabia Saudita', 'Japón y Corea', 'Estados Unidos, México y Canadá', 'D', 'EASY', TRUE),
    ('FÚTBOL', '¿En qué país se inventó el fútbol moderno?',
     'Brasil', 'Inglaterra', 'Argentina', 'Alemania', 'B', 'EASY', TRUE),

-- ---------------- MATEMÁTICAS (9 + 1 = 10) ----------------
    ('MATEMÁTICAS', '¿Cuánto es 12 × 12?',
     '124', '142', '122', '144', 'D', 'EASY', TRUE),
    ('MATEMÁTICAS', '¿Cuál es el resultado de 100 ÷ 4?',
     '20', '25', '30', '40', 'B', 'EASY', TRUE),
    ('MATEMÁTICAS', '¿Cuántos lados tiene un hexágono?',
     '5', '7', '6', '8', 'C', 'EASY', TRUE),
    ('MATEMÁTICAS', '¿Cuánto es 15 + 27?',
     '42', '32', '52', '37', 'A', 'EASY', TRUE),
    ('MATEMÁTICAS', '¿Cuál de estos números es primo?',
     '15', '21', '27', '17', 'D', 'EASY', TRUE),
    ('MATEMÁTICAS', '¿Cuánto es 9 × 9?',
     '81', '72', '91', '89', 'A', 'EASY', TRUE),
    ('MATEMÁTICAS', '¿Cuál es el valor de pi redondeado a dos decimales?',
     '3,14', '3,41', '3,15', '2,14', 'A', 'EASY', TRUE),
    ('MATEMÁTICAS', '¿Cuántos minutos hay en dos horas?',
     '60', '90', '120', '200', 'C', 'EASY', TRUE),
    ('MATEMÁTICAS', '¿Qué número sigue en la serie 2, 4, 6, 8, …?',
     '9', '10', '12', '14', 'B', 'EASY', TRUE),

-- ---------------- CIENCIA (9 + 1 = 10) ----------------
    ('CIENCIA', '¿Cuántos planetas tiene el sistema solar?',
     '7', '9', '10', '8', 'D', 'EASY', TRUE),
    ('CIENCIA', '¿Qué gas necesitamos respirar para vivir?',
     'Dióxido de carbono', 'Oxígeno', 'Nitrógeno', 'Helio', 'B', 'EASY', TRUE),
    ('CIENCIA', '¿Qué órgano del cuerpo bombea la sangre?',
     'El pulmón', 'El hígado', 'El corazón', 'El cerebro', 'C', 'EASY', TRUE),
    ('CIENCIA', '¿Qué necesitan las plantas para hacer la fotosíntesis?',
     'La luz del Sol', 'El sonido', 'La lluvia de noche', 'El viento', 'A', 'EASY', TRUE),
    ('CIENCIA', '¿A qué temperatura hierve el agua a nivel del mar?',
     '50 °C', '100 °C', '90 °C', '120 °C', 'B', 'EASY', TRUE),
    ('CIENCIA', '¿En qué estado de la materia se encuentra el hielo?',
     'Sólido', 'Líquido', 'Gaseoso', 'Plasma', 'A', 'EASY', TRUE),
    ('CIENCIA', '¿Quién formuló la teoría de la relatividad?',
     'Isaac Newton', 'Thomas Edison', 'Stephen Hawking', 'Albert Einstein', 'D', 'EASY', TRUE),
    ('CIENCIA', '¿Qué fuerza hace que los objetos caigan al suelo?',
     'La energía', 'La inercia', 'La gravedad', 'El magnetismo', 'C', 'EASY', TRUE),
    ('CIENCIA', '¿Cuál es el planeta más grande del sistema solar?',
     'Júpiter', 'Saturno', 'Neptuno', 'Urano', 'A', 'EASY', TRUE),

-- ---------------- HISTORIA (9 + 1 = 10) ----------------
    ('HISTORIA', '¿En qué país se construyó la Gran Muralla?',
     'China', 'Japón', 'India', 'Mongolia', 'A', 'EASY', TRUE),
    ('HISTORIA', '¿Quién pintó la Mona Lisa?',
     'Miguel Ángel', 'Pablo Picasso', 'Leonardo da Vinci', 'Vincent van Gogh', 'C', 'EASY', TRUE),
    ('HISTORIA', '¿Qué civilización construyó las pirámides de Giza?',
     'Los griegos', 'Los antiguos egipcios', 'Los romanos', 'Los mayas', 'B', 'EASY', TRUE),
    ('HISTORIA', '¿Quién fue el primer presidente de los Estados Unidos?',
     'Abraham Lincoln', 'Thomas Jefferson', 'John Adams', 'George Washington', 'D', 'EASY', TRUE),
    ('HISTORIA', '¿En qué continente aparecieron los primeros seres humanos?',
     'África', 'Asia', 'Europa', 'América', 'A', 'EASY', TRUE),
    ('HISTORIA', '¿Qué gran imperio de la antigüedad tuvo su capital en Roma?',
     'El imperio griego', 'El imperio romano', 'El imperio egipcio', 'El imperio persa', 'B', 'EASY', TRUE),
    ('HISTORIA', 'Según la leyenda, ¿quién gritó "¡Eureka!" al descubrir algo importante?',
     'Arquímedes', 'Sócrates', 'Pitágoras', 'Aristóteles', 'A', 'EASY', TRUE),
    ('HISTORIA', '¿Qué invento importante se le atribuye a Johannes Gutenberg?',
     'El teléfono', 'La bombilla', 'El avión', 'La imprenta', 'D', 'EASY', TRUE),
    ('HISTORIA', '¿Quién fue Cleopatra?',
     'Una reina de Grecia', 'Una reina de Roma', 'Una reina de Egipto', 'Una reina de Persia', 'C', 'EASY', TRUE),

-- ---------------- CULTURA GENERAL (9 + 1 = 10) ----------------
    ('CULTURA GENERAL', '¿Cuántos colores tiene el arcoíris?',
     '5', '6', '7', '8', 'C', 'EASY', TRUE),
    ('CULTURA GENERAL', '¿Qué día de la semana viene después del miércoles?',
     'Martes', 'Jueves', 'Viernes', 'Lunes', 'B', 'EASY', TRUE),
    ('CULTURA GENERAL', '¿Cuántas notas tiene la escala musical tradicional?',
     '5', '6', '7', '8', 'C', 'EASY', TRUE),
    ('CULTURA GENERAL', '¿Qué estación del año viene después del verano?',
     'Primavera', 'Invierno', 'Otoño', 'Verano otra vez', 'C', 'EASY', TRUE),
    ('CULTURA GENERAL', '¿Cuál de estos deportes se juega por equipos?',
     'Baloncesto', 'Natación', 'Atletismo', 'Gimnasia', 'A', 'EASY', TRUE),
    ('CULTURA GENERAL', '¿Cuál es la moneda oficial de Estados Unidos?',
     'El euro', 'El dólar', 'La libra', 'El peso', 'B', 'EASY', TRUE),
    ('CULTURA GENERAL', '¿Cuántos dedos tiene una persona en sus dos manos?',
     '10', '8', '12', '9', 'A', 'EASY', TRUE),
    ('CULTURA GENERAL', '¿Qué color se obtiene al mezclar azul y amarillo?',
     'Naranja', 'Morado', 'Verde', 'Rosa', 'C', 'EASY', TRUE),
    ('CULTURA GENERAL', '¿Cómo se llama el conjunto de todos los huesos del cuerpo?',
     'Los músculos', 'La piel', 'Los órganos', 'El esqueleto', 'D', 'EASY', TRUE),

-- ---------------- GEOGRAFÍA (9 + 1 = 10) ----------------
    ('GEOGRAFÍA', '¿Cuál es el océano más grande del mundo?',
     'Atlántico', 'Pacífico', 'Índico', 'Ártico', 'B', 'EASY', TRUE),
    ('GEOGRAFÍA', '¿En qué país se encuentra la Torre Eiffel?',
     'Francia', 'Italia', 'España', 'Inglaterra', 'A', 'EASY', TRUE),
    ('GEOGRAFÍA', '¿Cuál es la capital de España?',
     'Barcelona', 'Sevilla', 'Madrid', 'Valencia', 'C', 'EASY', TRUE),
    ('GEOGRAFÍA', '¿Cuál es el continente más grande del mundo?',
     'África', 'América', 'Europa', 'Asia', 'D', 'EASY', TRUE),
    ('GEOGRAFÍA', '¿Qué país tiene la forma de una bota?',
     'España', 'Italia', 'Portugal', 'Grecia', 'B', 'EASY', TRUE),
    ('GEOGRAFÍA', '¿Cuál es el desierto cálido más grande del mundo?',
     'Sáhara', 'Gobi', 'Atacama', 'Kalahari', 'A', 'EASY', TRUE),
    ('GEOGRAFÍA', '¿Cuál es la capital de México?',
     'Guadalajara', 'Monterrey', 'Ciudad de México', 'Puebla', 'C', 'EASY', TRUE),
    ('GEOGRAFÍA', '¿Cuál es la montaña más alta del mundo?',
     'El Aconcagua', 'El Kilimanjaro', 'El Mont Blanc', 'El Everest', 'D', 'EASY', TRUE),
    ('GEOGRAFÍA', '¿En qué país se encuentra el Cristo Redentor?',
     'Brasil', 'Argentina', 'Perú', 'Colombia', 'A', 'EASY', TRUE),

-- ---------------- ANIMALES (9 + 1 = 10) ----------------
    ('ANIMALES', '¿Cuántas patas tiene una araña?',
     '8', '6', '10', '4', 'A', 'EASY', TRUE),
    ('ANIMALES', '¿Qué animal cambia de color para camuflarse?',
     'El camaleón', 'El loro', 'La tortuga', 'El cangrejo', 'A', 'EASY', TRUE),
    ('ANIMALES', '¿Cuál es el animal terrestre más rápido?',
     'El león', 'El caballo', 'El guepardo', 'El perro', 'C', 'EASY', TRUE),
    ('ANIMALES', '¿Qué mamífero pone huevos?',
     'El murciélago', 'El delfín', 'La ballena', 'El ornitorrinco', 'D', 'EASY', TRUE),
    ('ANIMALES', '¿Cuál es el animal más grande del mundo?',
     'El elefante africano', 'La ballena azul', 'La jirafa', 'El tiburón blanco', 'B', 'EASY', TRUE),
    ('ANIMALES', '¿Qué animal puede dormir de pie?',
     'El caballo', 'El gato', 'El perro', 'El conejo', 'A', 'EASY', TRUE),
    ('ANIMALES', '¿Cómo se llama la cría de la rana?',
     'El polluelo', 'El potro', 'El renacuajo', 'El cachorro', 'C', 'EASY', TRUE),
    ('ANIMALES', '¿Qué ave no puede volar pero es una excelente nadadora?',
     'El águila', 'La gaviota', 'El colibrí', 'El pingüino', 'D', 'EASY', TRUE),
    ('ANIMALES', 'En muchos países dicen que un gato tiene…',
     '3 vidas', '7 vidas', '9 vidas', '1 vida', 'B', 'EASY', TRUE),

-- ---------------- TECNOLOGÍA (9 + 1 = 10) ----------------
    ('TECNOLOGÍA', '¿Qué dispositivo se usa para mover el cursor en la computadora?',
     'El teclado', 'La impresora', 'El ratón', 'La bocina', 'C', 'EASY', TRUE),
    ('TECNOLOGÍA', '¿Qué significan las letras "www" de una dirección web?',
     'World Wide Web', 'World Word Web', 'Web World Wide', 'Wide Web World', 'A', 'EASY', TRUE),
    ('TECNOLOGÍA', '¿Qué parte de la computadora se considera su "cerebro"?',
     'El teclado', 'El procesador', 'El monitor', 'La pantalla', 'B', 'EASY', TRUE),
    ('TECNOLOGÍA', '¿Cómo se llama en inglés un teléfono inteligente?',
     'Computer phone', 'Smartphone', 'Mobile laptop', 'Keyboard', 'B', 'EASY', TRUE),
    ('TECNOLOGÍA', '¿Qué usamos para escribir letras en la computadora?',
     'El teclado', 'El mouse', 'La impresora', 'El escáner', 'A', 'EASY', TRUE),
    ('TECNOLOGÍA', '¿Cómo se llama un programa malicioso que daña las computadoras?',
     'Un juego', 'Una aplicación', 'Un virus', 'Un navegador', 'C', 'EASY', TRUE),
    ('TECNOLOGÍA', '¿Quién fundó la empresa Microsoft?',
     'Steve Jobs', 'Bill Gates', 'Elon Musk', 'Jeff Bezos', 'B', 'EASY', TRUE),
    ('TECNOLOGÍA', '¿Cuál de estos es un buscador de internet?',
     'Google', 'Microsoft Word', 'Minecraft', 'WhatsApp', 'A', 'EASY', TRUE),
    ('TECNOLOGÍA', '¿Qué podemos guardar en una memoria USB?',
     'Agua', 'Batería', 'Datos y archivos', 'Sonido', 'C', 'EASY', TRUE);
