-- =============================================================
-- V4: +10 preguntas por categoría con dificultad MEDIUM
-- (20 por categoría -> 160 en total). La categoría FÚTBOL suma
-- preguntas sobre HISTORIA DEL FÚTBOL: mundiales pasados, equipos
-- y jugadores legendarios.
-- correct_option guarda la letra de la opción correcta (A-D).
-- =============================================================

INSERT INTO questions
    (category, question, option_a, option_b, option_c, option_d, correct_option, difficulty, active)
VALUES

-- ---------------- FÚTBOL: historia del fútbol (10 MEDIUM) ----------------
    ('FÚTBOL', '¿En qué año se jugó el primer Mundial de fútbol de la historia?',
     '1930', '1924', '1938', '1950', 'A', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué selección ganó el primer Mundial de la historia (1930)?',
     'Brasil', 'Uruguay', 'Italia', 'Argentina', 'B', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué selección ganó el Mundial de 1978, jugado en su propio país?',
     'Países Bajos', 'Italia', 'Argentina', 'Alemania', 'C', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué leyenda del fútbol brasileño es conocido como "O Rei" (el Rey)?',
     'Ronaldo', 'Ronaldinho', 'Kaká', 'Pelé', 'D', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿En qué país se celebró el Mundial de Fútbol de 2014?',
     'Brasil', 'Rusia', 'Sudáfrica', 'Catar', 'A', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué equipo ha ganado más veces la Champions League (hasta 2024)?',
     'Barcelona', 'Real Madrid', 'Liverpool', 'Ajax', 'B', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué jugador marcó el famoso gol de "la Mano de Dios" en un Mundial?',
     'Pelé', 'Zinedine Zidane', 'Diego Maradona', 'Lionel Messi', 'C', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué selección ganó el Mundial de Fútbol de 2018?',
     'Croacia', 'Bélgica', 'Inglaterra', 'Francia', 'D', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Cómo se llama el partido entre el Real Madrid y el Barcelona?',
     'El Clásico', 'El Derbi', 'El Superclásico', 'La Final', 'A', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué jugador portugués es conocido como "CR7"?',
     'Nani', 'Cristiano Ronaldo', 'Pepe', 'Eusébio', 'B', 'MEDIUM', TRUE),

-- ---------------- MATEMÁTICAS (10 MEDIUM) ----------------
    ('MATEMÁTICAS', '¿Cuánto es el 25 % de 200?',
     '25', '40', '50', '75', 'C', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuál es el área de un cuadrado cuyo lado mide 5?',
     '10', '15', '20', '25', 'D', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuánto es 3 elevado a la cuarta (3⁴)?',
     '81', '27', '64', '12', 'A', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuál es la raíz cuadrada de 144?',
     '11', '12', '14', '16', 'B', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuánto es 17 + 29 + 15?',
     '55', '59', '61', '63', 'C', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuál es el mínimo común múltiplo de 4 y 6?',
     '10', '18', '24', '12', 'D', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Qué fracción equivale a 0,5?',
     '1/2', '1/4', '2/3', '3/4', 'A', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuántos grados suman los ángulos internos de un triángulo?',
     '90', '180', '270', '360', 'B', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuánto es 7 × 13?',
     '81', '84', '91', '93', 'C', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuál es el número primo que sigue después del 13?',
     '15', '16', '19', '17', 'D', 'MEDIUM', TRUE),

-- ---------------- CIENCIA (10 MEDIUM) ----------------
    ('CIENCIA', '¿Cuál es el órgano más grande del cuerpo humano?',
     'La piel', 'El hígado', 'Los pulmones', 'El cerebro', 'A', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Qué planeta es conocido como "el planeta rojo"?',
     'Venus', 'Marte', 'Júpiter', 'Mercurio', 'B', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Cuántos huesos tiene, aproximadamente, un adulto?',
     '106', '156', '206', '306', 'C', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Qué mide un termómetro?',
     'La presión', 'La velocidad', 'El peso', 'La temperatura', 'D', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Cuál es el satélite natural de la Tierra?',
     'La Luna', 'Fobos', 'Europa', 'Titán', 'A', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Qué metal es líquido a temperatura ambiente?',
     'Hierro', 'Mercurio', 'Plata', 'Estaño', 'B', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Qué parte de la célula es su "centro de control"?',
     'La membrana', 'El citoplasma', 'El núcleo', 'La pared celular', 'C', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Cuántos dientes tiene, aproximadamente, un adulto?',
     '20', '24', '28', '32', 'D', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Cuál de estos NO es un estado de la materia?',
     'La luz', 'El sólido', 'El líquido', 'El gas', 'A', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Quién descubrió la penicilina?',
     'Marie Curie', 'Alexander Fleming', 'Louis Pasteur', 'Isaac Newton', 'B', 'MEDIUM', TRUE),

-- ---------------- HISTORIA (10 MEDIUM) ----------------
    ('HISTORIA', '¿En qué año cayó el Imperio romano de Occidente?',
     '476', '1066', '1492', '1453', 'A', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Qué faraón egipcio se hizo famoso por su tumba encontrada casi intacta?',
     'Ramsés II', 'Tutankamón', 'Keops', 'Akenatón', 'B', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Qué imperio construyó Machu Picchu?',
     'Los aztecas', 'Los mayas', 'Los incas', 'Los olmecas', 'C', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Quién es conocido como el "padre de la patria" de la independencia de México?',
     'José Martí', 'José de San Martín', 'Simón Bolívar', 'Miguel Hidalgo', 'D', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Quién fue emperador de Francia a comienzos del siglo XIX?',
     'Napoleón Bonaparte', 'Luis XVI', 'Carlomagno', 'Maximiliano', 'A', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Qué pueblo inventó la escritura cuneiforme?',
     'Los egipcios', 'Los sumerios', 'Los griegos', 'Los fenicios', 'B', 'MEDIUM', TRUE),
    ('HISTORIA', '¿En qué año comenzó la Segunda Guerra Mundial?',
     '1914', '1918', '1939', '1945', 'C', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Qué muro famoso fue derribado en Berlín en 1989?',
     'El Muro de Adriano', 'El Muro de las Lamentaciones', 'La Gran Muralla', 'El Muro de Berlín', 'D', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Qué país fue el primero en llevar seres humanos a la Luna?',
     'Estados Unidos', 'Unión Soviética', 'China', 'Japón', 'A', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Quién fue Simón Bolívar?',
     'Un rey de España', 'Un libertador de varios países de Sudamérica', 'Un explorador de la Antártida', 'Un faraón de Egipto', 'B', 'MEDIUM', TRUE),

-- ---------------- CULTURA GENERAL (10 MEDIUM) ----------------
    ('CULTURA GENERAL', '¿Cuántos jugadores tiene cada equipo en un partido de béisbol?',
     '7', '8', '9', '11', 'C', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Qué país inventó el papel?',
     'Egipto', 'Grecia', 'Roma', 'China', 'D', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Quién escribió "Cien años de soledad"?',
     'Gabriel García Márquez', 'Pablo Neruda', 'Mario Vargas Llosa', 'Jorge Luis Borges', 'A', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Cuál es la capital de Japón?',
     'Osaka', 'Tokio', 'Kioto', 'Hiroshima', 'B', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Cuántas teclas tiene un piano?',
     '66', '76', '88', '96', 'C', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Cuántos continentes hay en el modelo más usado en las escuelas?',
     '5', '6', '8', '7', 'D', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Qué deporte se juega en el torneo de Wimbledon?',
     'Tenis', 'Golf', 'Fórmula 1', 'Remo', 'A', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Cuál es la estrella más cercana a la Tierra?',
     'Sirio', 'El Sol', 'Próxima Centauri', 'Vega', 'B', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Cuál es la moneda oficial de Japón?',
     'El yuan', 'El won', 'El yen', 'El dólar', 'C', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Qué comida de Italia es famosa en todo el mundo?',
     'El sushi', 'El taco', 'El curry', 'La pizza', 'D', 'MEDIUM', TRUE),

-- ---------------- GEOGRAFÍA (10 MEDIUM) ----------------
    ('GEOGRAFÍA', '¿Cuál es la capital de Argentina?',
     'Buenos Aires', 'Rosario', 'Córdoba', 'Mendoza', 'A', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Qué río atraviesa la ciudad de París?',
     'El Ródano', 'El Sena', 'El Garona', 'El Loira', 'B', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿En qué continente se encuentra el país de Australia?',
     'Asia', 'Europa', 'Oceanía', 'África', 'C', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Qué país de América Latina tiene más habitantes?',
     'México', 'Colombia', 'Argentina', 'Brasil', 'D', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Qué cordillera separa Europa de Asia?',
     'Los Urales', 'Los Alpes', 'El Himalaya', 'Los Andes', 'A', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Entre qué países se encuentra el lago Titicaca?',
     'Chile y Bolivia', 'Perú y Bolivia', 'Perú y Chile', 'Argentina y Bolivia', 'B', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Cuál es la capital de Canadá?',
     'Toronto', 'Vancouver', 'Ottawa', 'Montreal', 'C', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Qué mar separa Europa de África?',
     'El mar Rojo', 'El mar Negro', 'El mar Báltico', 'El mar Mediterráneo', 'D', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Cuál es el país más pequeño del mundo?',
     'Ciudad del Vaticano', 'Mónaco', 'San Marino', 'Liechtenstein', 'A', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Cuál es la capital de Australia?',
     'Sídney', 'Canberra', 'Melbourne', 'Perth', 'B', 'MEDIUM', TRUE),

-- ---------------- ANIMALES (10 MEDIUM) ----------------
    ('ANIMALES', '¿Qué animal tiene el cuello más largo?',
     'La cebra', 'El camello', 'La jirafa', 'El avestruz', 'C', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Cuál es el ave más rápida del mundo cuando se lanza en picada?',
     'El águila real', 'El cóndor', 'El búho', 'El halcón peregrino', 'D', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Qué pez se infla para defenderse de sus enemigos?',
     'El pez globo', 'El tiburón', 'La sardina', 'El salmón', 'A', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Cómo se llama el sonido que hace el león?',
     'El aullido', 'El rugido', 'El relincho', 'El graznido', 'B', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Qué insecto produce la miel?',
     'La avispa', 'La hormiga', 'La abeja', 'La mariposa', 'C', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Qué animal duerme todo el invierno (hiberna)?',
     'El conejo', 'El perro', 'El caballo', 'El oso', 'D', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Cuántos corazones tiene un pulpo?',
     '3', '1', '2', '5', 'A', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Qué animal tiene rayas blancas y negras?',
     'El tigre', 'La cebra', 'La vaca', 'El oso panda', 'B', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Cómo se llama el grupo de lobos?',
     'La bandada', 'El rebaño', 'La manada', 'El cardumen', 'C', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Qué reptil suelta su cola para escapar de un peligro?',
     'La serpiente', 'La rana', 'La tortuga', 'La lagartija', 'D', 'MEDIUM', TRUE),

-- ---------------- TECNOLOGÍA (10 MEDIUM) ----------------
    ('TECNOLOGÍA', '¿Qué empresa creó el sistema operativo Android?',
     'Google', 'Apple', 'Microsoft', 'Samsung', 'A', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué significa la sigla RAM en una computadora?',
     'Memoria de Acceso Rápido', 'Memoria de Acceso Aleatorio', 'Memoria Activa Recargable', 'Red de Acceso Móvil', 'B', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿En qué año se lanzó el primer iPhone?',
     '2001', '2004', '2007', '2010', 'C', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué red conecta computadoras de todo el mundo?',
     'La intranet', 'El bluetooth', 'El USB', 'Internet', 'D', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué lenguaje se usa para crear páginas web?',
     'HTML', 'Java', 'Python', 'Scratch', 'A', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué dispositivo se usa para jugar videojuegos con las manos?',
     'El monitor', 'El control', 'La impresora', 'El módem', 'B', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué disco almacena más información?',
     'Un DVD', 'Un CD', 'Un Blu-ray', 'Un casete', 'C', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Cómo se llama la parte física de una computadora?',
     'El software', 'El programa', 'La aplicación', 'El hardware', 'D', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Cuántos bits forman un byte?',
     '8', '4', '16', '2', 'A', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿A cuánto equivale 1024 megabytes (MB)?',
     'A 1 kilobyte', 'A 1 gigabyte', 'A 1 terabyte', 'A 1 bit', 'B', 'MEDIUM', TRUE);
