-- =============================================================
-- V6: nueva categoría PELÍCULAS (Disney infantiles + películas famosas,
-- 25 preguntas) y +10 preguntas (5 MEDIUM + 5 HARD) a cada categoría
-- existente. Generado programáticamente: las letras de correct_option se
-- rotan para repartir A-D; el texto correcto siempre coincide con su letra.
-- =============================================================

INSERT INTO questions
    (category, question, option_a, option_b, option_c, option_d, correct_option, difficulty, active)
VALUES
    ('PELÍCULAS', '¿Qué princesa de Disney vive bajo el mar y se llama Ariel?',
     'La Sirenita', 'Blancanieves', 'Cenicienta', 'Mulán', 'A', 'EASY', TRUE),
    ('PELÍCULAS', '¿Cómo se llama el muñeco de madera que quería convertirse en un niño de verdad?',
     'Rayo McQueen', 'Pinocho', 'Simba', 'Bambi', 'B', 'EASY', TRUE),
    ('PELÍCULAS', '¿Qué película de Disney cuenta la historia de un león llamado Simba?',
     'La Dama y el Vagabundo', 'El Libro de la Selva', 'El Rey León', 'Buscando a Nemo', 'C', 'EASY', TRUE),
    ('PELÍCULAS', '¿Cómo se llama la hermana menor de Elsa en "Frozen"?',
     'Aurora', 'Rapunzel', 'Bella', 'Anna', 'D', 'EASY', TRUE),
    ('PELÍCULAS', '¿Qué perrito es el mejor amigo de Mickey Mouse?',
     'Pluto', 'Goofy', 'Donald', 'Simba', 'A', 'EASY', TRUE),
    ('PELÍCULAS', '¿En qué película aparece el vaquero Woody y el astronauta Buzz Lightyear?',
     'Cars', 'Toy Story', 'Monsters, Inc.', 'Up', 'B', 'EASY', TRUE),
    ('PELÍCULAS', '¿Cómo se llama el elefante que puede volar con sus orejas?',
     'Bambi', 'Dory', 'Dumbo', 'Nemo', 'C', 'EASY', TRUE),
    ('PELÍCULAS', '¿Qué princesa de Disney rompió el hechizo al besar a una rana?',
     'Ariel', 'Jasmín', 'Blanca Nieves', 'Tiana', 'D', 'EASY', TRUE),
    ('PELÍCULAS', '¿Cómo se llama el pato gruñón, amigo de Mickey Mouse?',
     'El Pato Donald', 'El Pato Lucas', 'Goofy', 'Pluto', 'A', 'EASY', TRUE),
    ('PELÍCULAS', '¿Qué película famosa tiene como protagonista a un niño mago llamado Harry?',
     'El Señor de los Anillos', 'Harry Potter', 'Narnia', 'Percy Jackson', 'B', 'EASY', TRUE),
    ('PELÍCULAS', '¿De qué película de Disney es la canción "Hakuna Matata"?',
     'Aladdín', 'Pocahontas', 'El Rey León', 'Tarzan', 'C', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Cómo se llama la isla donde vive Moana?',
     'Agrabah', 'Arendelle', 'Neverland', 'Motunui', 'D', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Qué película de Disney muestra a una familia de superhéroes llamada los Parr?',
     'Los Increíbles', 'Big Hero 6', 'Zootopia', 'Coco', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿En qué película aparece la pececita Dory, que olvida todo?',
     'La Sirenita', 'Buscando a Nemo', 'Shark Tale', 'El viaje de Arlo', 'B', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Qué villana de Disney quiere deshacerse de Blancanieves?',
     'Úrsula', 'Maléfica', 'La Reina Malvada', 'Cruella', 'C', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿De qué saga infantil famosa es el personaje del Gato con Botas?',
     'Ice Age', 'Madagascar', 'Kung Fu Panda', 'Shrek', 'D', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Qué película de Disney cuenta la historia de un robot que limpia la Tierra?',
     'WALL·E', 'Robots', 'Big Hero 6', 'Metrópolis', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Cómo se llama el reino ficticio donde viven Elsa y Anna?',
     'Motunui', 'Arendelle', 'Corona', 'Atlántica', 'B', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿En qué película aparecen los monstruos Sulley y Mike?',
     'Toy Story', 'Cars', 'Monsters, Inc.', 'Ratatouille', 'C', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Qué película de Disney transcurre en la ciudad de Agrabah?',
     'Mulán', 'El Rey León', 'Hércules', 'Aladdín', 'D', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Cuál fue la primera película animada de Disney, estrenada en 1937?',
     'Blancanieves y los siete enanitos', 'Pinocho', 'Fantasía', 'Dumbo', 'A', 'HARD', TRUE),
    ('PELÍCULAS', '¿Cómo se llama la bruja del mar en "La Sirenita"?',
     'Maléfica', 'Úrsula', 'Cruella', 'La Reina Malvada', 'B', 'HARD', TRUE),
    ('PELÍCULAS', '¿En qué año se estrenó "Toy Story", la primera película animada por computadora?',
     '1989', '1999', '1995', '2001', 'C', 'HARD', TRUE),
    ('PELÍCULAS', '¿En qué película de Disney aparece el dragón Mushu?',
     'Aladdín', 'Hércules', 'Pocahontas', 'Mulán', 'D', 'HARD', TRUE),
    ('PELÍCULAS', '¿Qué princesa de Disney vivió encerrada en una torre con cabello mágico muy largo?',
     'Rapunzel', 'Frozen', 'Valiente', 'Mulán', 'A', 'HARD', TRUE),
    ('FÚTBOL', '¿Qué selección ganó el famoso Mundial de 1950 jugado en Brasil (el "Maracanazo")?',
     'Brasil', 'Uruguay', 'Argentina', 'Italia', 'B', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Cuántas Copas del Mundo ha ganado Alemania?',
     '3', '5', '4', '6', 'C', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿En qué club jugó Pelé la mayor parte de su carrera?',
     'Flamengo', 'River Plate', 'Boca Juniors', 'Santos FC', 'D', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué selección ganó la Copa América de 2021?',
     'Argentina', 'Brasil', 'Uruguay', 'Colombia', 'A', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Cómo se llama el estadio del Barcelona, conocido como "el templo"?',
     'Santiago Bernabéu', 'Camp Nou', 'Wembley', 'Maracaná', 'B', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué país europeo organizó el Mundial de Fútbol de 1954?',
     'Italia', 'Inglaterra', 'Suiza', 'Francia', 'C', 'HARD', TRUE),
    ('FÚTBOL', '¿Qué portero legendario era conocido como "la Araña Negra"?',
     'Gordon Banks', 'Dino Zoff', 'Iker Casillas', 'Lev Yashin', 'D', 'HARD', TRUE),
    ('FÚTBOL', '¿En qué año la Copa de Europa pasó a llamarse Champions League?',
     '1992', '1985', '1998', '2000', 'A', 'HARD', TRUE),
    ('FÚTBOL', '¿Qué selección ganó el Mundial de Fútbol de 2010?',
     'Países Bajos', 'España', 'Alemania', 'Brasil', 'B', 'HARD', TRUE),
    ('FÚTBOL', '¿Qué club argentino ha ganado más veces la Copa Libertadores?',
     'Boca Juniors', 'River Plate', 'Independiente', 'Estudiantes', 'C', 'HARD', TRUE),
    ('MATEMÁTICAS', '¿Cuánto es el 10 % de 250?',
     '15', '20', '30', '25', 'D', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Qué número sigue en la serie 1, 1, 2, 3, 5, 8, …?',
     '13', '10', '11', '12', 'A', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuántos segundos tiene una hora?',
     '600', '3600', '1800', '60', 'B', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuántas decenas tiene el número 350?',
     '3', '5', '35', '350', 'C', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Qué número es mayor: 0,7 o 0,19?',
     '0,19', 'Son iguales', 'Depende', '0,7', 'D', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', 'Si un triángulo tiene dos ángulos de 60°, ¿cuánto mide el tercero?',
     '60°', '30°', '90°', '120°', 'A', 'HARD', TRUE),
    ('MATEMÁTICAS', '¿Cuánto es (−3) × (−4)?',
     '−12', '12', '7', '−7', 'B', 'HARD', TRUE),
    ('MATEMÁTICAS', '¿Cuál es el valor de 5 elevado al cubo (5³)?',
     '25', '100', '125', '250', 'C', 'HARD', TRUE),
    ('MATEMÁTICAS', '¿Qué porcentaje representa 3 de 15?',
     '15 %', '25 %', '30 %', '20 %', 'D', 'HARD', TRUE),
    ('MATEMÁTICAS', '¿Cuántas caras tiene un cubo?',
     '6', '4', '8', '12', 'A', 'HARD', TRUE),
    ('CIENCIA', '¿Qué vitamina produce nuestro cuerpo con la luz del sol?',
     'Vitamina C', 'Vitamina D', 'Vitamina A', 'Vitamina B12', 'B', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Qué animal marino puede formar una perla dentro de su concha?',
     'El mejillón', 'El cangrejo', 'La ostra', 'La estrella de mar', 'C', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Cómo se llama la capa externa de la Tierra?',
     'El manto', 'El núcleo', 'La atmósfera', 'La corteza', 'D', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Cómo se llama el científico que estudia las estrellas y los planetas?',
     'Astrónomo', 'Geólogo', 'Biólogo', 'Químico', 'A', 'MEDIUM', TRUE),
    ('CIENCIA', '¿En qué estado de la materia se encuentra el vapor de agua?',
     'Sólido', 'Gaseoso', 'Líquido', 'Plasma', 'B', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Cuántas patas tiene un insecto adulto?',
     '4', '8', '6', '10', 'C', 'HARD', TRUE),
    ('CIENCIA', '¿Qué hace que los barcos floten en el agua?',
     'La gravedad', 'La presión del aire', 'El magnetismo', 'El empuje (flotabilidad)', 'D', 'HARD', TRUE),
    ('CIENCIA', '¿Qué planeta tiene el día más corto del sistema solar?',
     'Júpiter', 'Marte', 'Mercurio', 'Neptuno', 'A', 'HARD', TRUE),
    ('CIENCIA', '¿Qué órgano produce la bilis, que ayuda a digerir las grasas?',
     'El páncreas', 'El hígado', 'El estómago', 'El bazo', 'B', 'HARD', TRUE),
    ('CIENCIA', '¿Qué tipo de roca se forma cuando el magma se enfría?',
     'Sedimentaria', 'Metamórfica', 'Ígnea', 'Ninguna', 'C', 'HARD', TRUE),
    ('HISTORIA', '¿Qué faraón mandó construir la Gran Pirámide de Giza?',
     'Tutankamón', 'Ramsés II', 'Cleopatra', 'Keops', 'D', 'MEDIUM', TRUE),
    ('HISTORIA', '¿En qué país europeo nació el Renacimiento?',
     'Italia', 'Francia', 'España', 'Alemania', 'A', 'MEDIUM', TRUE),
    ('HISTORIA', '¿En qué batalla fue derrotado Napoleón en 1815?',
     'Trafalgar', 'Waterloo', 'Austerlitz', 'Borodino', 'B', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Cómo se llamaba el barco en el que viajó Charles Darwin?',
     'El Mayflower', 'La Santa María', 'El Beagle', 'El Titanic', 'C', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Qué civilización construyó el Coliseo de Roma?',
     'La griega', 'La egipcia', 'La fenicia', 'La romana', 'D', 'MEDIUM', TRUE),
    ('HISTORIA', '¿En qué año se firmó la Declaración de Independencia de Estados Unidos?',
     '1776', '1492', '1810', '1918', 'A', 'HARD', TRUE),
    ('HISTORIA', '¿Quién fue la primera mujer en ganar un Premio Nobel?',
     'Rosa Parks', 'Marie Curie', 'Ada Lovelace', 'Jane Goodall', 'B', 'HARD', TRUE),
    ('HISTORIA', '¿Qué civilización antigua creó el calendario de 365 días?',
     'La romana', 'La griega', 'La egipcia', 'La maya', 'C', 'HARD', TRUE),
    ('HISTORIA', '¿Quién fue el último emperador de los incas?',
     'Huayna Cápac', 'Pachacútec', 'Manco Cápac', 'Atahualpa', 'D', 'HARD', TRUE),
    ('HISTORIA', '¿Qué explorador llegó a la India por mar rodeando África en 1498?',
     'Vasco da Gama', 'Cristóbal Colón', 'Magallanes', 'Hernán Cortés', 'A', 'HARD', TRUE),
    ('CULTURA GENERAL', '¿Cuántas cuerdas tiene una guitarra clásica?',
     '4', '6', '5', '7', 'B', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Qué color se obtiene al mezclar rojo y blanco?',
     'Naranja', 'Morado', 'Rosa', 'Marrón', 'C', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Cuál es la capital de Brasil?',
     'Río de Janeiro', 'São Paulo', 'Salvador', 'Brasilia', 'D', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Cuántos jugadores tiene en cancha un equipo de voleibol?',
     '6', '5', '7', '9', 'A', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Qué planeta brilla al atardecer y llaman "la estrella de la tarde"?',
     'Marte', 'Venus', 'Mercurio', 'Júpiter', 'B', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Quién escribió "Romeo y Julieta"?',
     'Charles Dickens', 'Miguel de Cervantes', 'William Shakespeare', 'Edgar Allan Poe', 'C', 'HARD', TRUE),
    ('CULTURA GENERAL', '¿Cuántos minutos tiene un día completo?',
     '720', '1200', '2880', '1440', 'D', 'HARD', TRUE),
    ('CULTURA GENERAL', '¿Qué famosa obra de Leonardo da Vinci representa la última cena de Jesús?',
     'La Última Cena', 'La Gioconda', 'La Creación de Adán', 'El Guernica', 'A', 'HARD', TRUE),
    ('CULTURA GENERAL', '¿Cuántas piezas tiene en total un juego de ajedrez?',
     '16', '32', '24', '64', 'B', 'HARD', TRUE),
    ('CULTURA GENERAL', '¿Qué famosa estatua regaló Francia a Estados Unidos?',
     'El Cristo Redentor', 'La Venus de Milo', 'La Estatua de la Libertad', 'El David', 'C', 'HARD', TRUE),
    ('GEOGRAFÍA', '¿Cuál es la capital de Perú?',
     'Bogotá', 'Quito', 'Santiago', 'Lima', 'D', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Qué país africano tiene la forma de un "cuerno"?',
     'Somalia', 'Egipto', 'Marruecos', 'Nigeria', 'A', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Cuál es el lago más grande del mundo?',
     'El lago Victoria', 'El mar Caspio', 'El lago Superior', 'El Titicaca', 'B', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿En qué continente nace el río Nilo?',
     'Asia', 'Europa', 'África', 'América', 'C', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Cuál es la capital de Portugal?',
     'Oporto', 'Madrid', 'Barcelona', 'Lisboa', 'D', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Cuál es el país más grande de América del Sur?',
     'Brasil', 'Argentina', 'Perú', 'Colombia', 'A', 'HARD', TRUE),
    ('GEOGRAFÍA', '¿Cuál es la capital de Turquía?',
     'Estambul', 'Ankara', 'Esmirna', 'Bursa', 'B', 'HARD', TRUE),
    ('GEOGRAFÍA', '¿Qué océano rodea el Polo Norte?',
     'El Pacífico', 'El Atlántico', 'El Ártico', 'El Índico', 'C', 'HARD', TRUE),
    ('GEOGRAFÍA', '¿Cuál es la isla más grande del mundo?',
     'Madagascar', 'Borneo', 'Australia', 'Groenlandia', 'D', 'HARD', TRUE),
    ('GEOGRAFÍA', '¿Qué desierto se encuentra en el norte de Chile?',
     'El de Atacama', 'El Sáhara', 'El Gobi', 'El Kalahari', 'A', 'HARD', TRUE),
    ('ANIMALES', '¿Qué ave no puede volar y es la más grande del mundo?',
     'El pingüino', 'El avestruz', 'El ñandú', 'El emú', 'B', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Cuántos estómagos tiene una vaca?',
     '1', '2', '4', '3', 'C', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Qué ballena es famosa por sus largos y melodiosos cantos?',
     'La azul', 'La orca', 'El delfín', 'La jorobada', 'D', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Qué insecto emite luz propia en la oscuridad?',
     'La luciérnaga', 'La libélula', 'La avispa', 'El grillo', 'A', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Cómo se llama la "casa" dura que protege al caracol?',
     'El caparazón del cangrejo', 'La concha', 'El nido', 'El coral', 'B', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Qué reptil tiene la lengua más larga en proporción a su cuerpo?',
     'La serpiente', 'El cocodrilo', 'El camaleón', 'La iguana', 'C', 'HARD', TRUE),
    ('ANIMALES', '¿Aproximadamente cuántos dientes puede tener un tiburón blanco en varias filas?',
     '20', '60', '100', '300', 'D', 'HARD', TRUE),
    ('ANIMALES', '¿Qué animal puede vivir más de 150 años?',
     'La tortuga gigante', 'El elefante', 'El loro', 'El caballo', 'A', 'HARD', TRUE),
    ('ANIMALES', '¿Qué ave se asocia con la sabiduría en la cultura popular?',
     'El cuervo', 'El búho', 'El águila', 'El loro', 'B', 'HARD', TRUE),
    ('ANIMALES', '¿Cómo se llama el sonido que hace el elefante?',
     'El rugido', 'El relincho', 'El barrito', 'El aullido', 'C', 'HARD', TRUE),
    ('TECNOLOGÍA', '¿Qué empresa desarrolló el sistema operativo Windows?',
     'Apple', 'Google', 'IBM', 'Microsoft', 'D', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué tecnología inalámbrica usas para conectar tu celular al internet de tu casa?',
     'WiFi', 'Bluetooth', 'USB', 'HDMI', 'A', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Cómo se llama el programa que usas para ver páginas web?',
     'Procesador', 'Navegador', 'Antivirus', 'Compresor', 'B', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿En qué unidad se mide la velocidad de un procesador?',
     'GB', 'MB', 'GHz', 'MHz de RAM', 'C', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué empresa fabrica el iPhone?',
     'Samsung', 'Xiaomi', 'Huawei', 'Apple', 'D', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué significa la sigla PDF?',
     'Formato de Documento Portátil', 'Proceso Digital de Fotos', 'Programa de Diseño Final', 'Portable Drive File', 'A', 'HARD', TRUE),
    ('TECNOLOGÍA', '¿Qué lenguaje se usa para dar estilo y color a las páginas web?',
     'HTML', 'CSS', 'Java', 'Python', 'B', 'HARD', TRUE),
    ('TECNOLOGÍA', '¿Qué significa la sigla LAN?',
     'Red Automática Nacional', 'Línea de Acceso Nuevo', 'Red de Área Local', 'Local Area Net', 'C', 'HARD', TRUE),
    ('TECNOLOGÍA', '¿Quién creó la primera página web de la historia?',
     'Bill Gates', 'Steve Jobs', 'Mark Zuckerberg', 'Tim Berners-Lee', 'D', 'HARD', TRUE),
    ('TECNOLOGÍA', '¿Qué significa la "G" de la red 5G?',
     'Generación', 'Global', 'Gigabyte', 'Gigahertz', 'A', 'HARD', TRUE);
