-- =============================================================
-- V7: +196 preguntas (V7 fusionado)
--  - +106 filas MEDIUM/EASY aportadas
--  - +90 preguntas MEDIUM nuevas por categoría (9 categorías)
-- Generado programáticamente: cada correct_option coincide con su
-- opción. Banco total al aplicar: 305 + 196 = 501.
-- =============================================================

INSERT INTO questions
    (category, question, option_a, option_b, option_c, option_d, correct_option, difficulty, active)
VALUES
    ('FÚTBOL', '¿Cada cuántos años se celebra el Mundial de Fútbol?',
     '4', '2', '6', '3', 'A', 'EASY', TRUE),
    ('FÚTBOL', '¿Cuántos jugadores conforman un equipo de fútbol dentro de la cancha?',
     '9', '10', '11', '12', 'C', 'EASY', TRUE),
    ('FÚTBOL', '¿Qué país fue la sede del Mundial de Fútbol de 2014?',
     'Alemania', 'Brasil', 'Sudáfrica', 'Rusia', 'B', 'EASY', TRUE),
    ('FÚTBOL', '¿Cómo se le conoce comúnmente al trofeo que reciben los campeones del Mundial?',
     'Copa Libertadores', 'Balón de Oro', 'Copa del Mundo', 'Champions League', 'C', 'EASY', TRUE),
    ('FÚTBOL', '¿Qué futbolista argentino es apodado "La Pulga"?',
     'Diego Maradona', 'Lionel Messi', 'Sergio Agüero', 'Ángel Di María', 'B', 'EASY', TRUE),
    ('FÚTBOL', '¿Qué selección ganó el primer Mundial de Fútbol, en 1930?',
     'Argentina', 'Brasil', 'Uruguay', 'Italia', 'C', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué selección ha ganado más Copas del Mundo en la historia?',
     'Alemania', 'Argentina', 'Italia', 'Brasil', 'D', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿En qué país se realizó el Mundial de Fútbol de 2018?',
     'Qatar', 'Rusia', 'Brasil', 'Francia', 'B', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Cómo se le conoce popularmente al Real Madrid?',
     'Los Blaugranas', 'Los Colchoneros', 'El Merengue', 'Los Red Devils', 'C', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué futbolista portugués es conocido por el apodo "CR7"?',
     'Cristiano Ronaldo', 'Ronaldinho', 'Ronaldo Nazário', 'Rui Costa', 'A', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuánto es 8 + 7?',
     '14', '15', '16', '17', 'B', 'EASY', TRUE),
    ('MATEMÁTICAS', '¿Cuánto es 9 × 3?',
     '27', '24', '18', '21', 'A', 'EASY', TRUE),
    ('MATEMÁTICAS', '¿Cuál es la mitad de 50?',
     '20', '30', '25', '15', 'C', 'EASY', TRUE),
    ('MATEMÁTICAS', '¿Cuánto es 100 − 45?',
     '45', '65', '50', '55', 'D', 'EASY', TRUE),
    ('MATEMÁTICAS', '¿Cuánto es 144 ÷ 12?',
     '11', '13', '12', '14', 'C', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuántos grados mide un ángulo recto?',
     '45°', '180°', '360°', '90°', 'D', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuál es el número primo más pequeño mayor que 10?',
     '12', '13', '11', '15', 'C', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', 'Un rectángulo mide 8 cm de largo y 5 cm de ancho, ¿cuál es su área?',
     '13 cm²', '40 cm²', '35 cm²', '45 cm²', 'B', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Qué necesitan las plantas, además de agua y tierra, para hacer la fotosíntesis?',
     'Luz solar', 'Oscuridad', 'Frío', 'Sal', 'A', 'EASY', TRUE),
    ('CIENCIA', '¿Cuántos huesos tiene aproximadamente el cuerpo humano adulto?',
     '106', '206', '306', '156', 'B', 'EASY', TRUE),
    ('CIENCIA', '¿En qué estado se encuentra el agua cuando es hielo?',
     'Líquido', 'Gaseoso', 'Sólido', 'Plasma', 'C', 'EASY', TRUE),
    ('CIENCIA', '¿Qué órgano se encarga de bombear la sangre por el cuerpo?',
     'El pulmón', 'El hígado', 'El cerebro', 'El corazón', 'D', 'EASY', TRUE),
    ('CIENCIA', '¿Cómo se llama el proceso mediante el cual las plantas producen su alimento?',
     'Respiración', 'Fotosíntesis', 'Digestión', 'Evaporación', 'B', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Qué gas es esencial para que los seres humanos puedan respirar?',
     'Nitrógeno', 'Dióxido de carbono', 'Oxígeno', 'Hidrógeno', 'C', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Qué parte de la célula controla sus actividades y contiene el ADN?',
     'La membrana', 'El citoplasma', 'El núcleo', 'La mitocondria', 'C', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Qué fuerza hace que los objetos caigan hacia el suelo?',
     'El magnetismo', 'La gravedad', 'La fricción', 'La electricidad', 'B', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Cuál es la fuente principal de energía para la Tierra?',
     'La Luna', 'El Sol', 'El viento', 'El agua', 'B', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Quién llegó a América en 1492?',
     'Vasco da Gama', 'Cristóbal Colón', 'Fernando de Magallanes', 'Marco Polo', 'B', 'EASY', TRUE),
    ('HISTORIA', '¿En qué continente se encuentran las famosas pirámides de Egipto?',
     'Asia', 'Europa', 'África', 'América', 'C', 'EASY', TRUE),
    ('HISTORIA', '¿Cómo se llamaban los antiguos guerreros de Japón?',
     'Vikingos', 'Samuráis', 'Espartanos', 'Legionarios', 'B', 'EASY', TRUE),
    ('HISTORIA', '¿Qué antigua civilización construyó el Coliseo?',
     'Los griegos', 'Los egipcios', 'Los romanos', 'Los persas', 'C', 'EASY', TRUE),
    ('HISTORIA', 'Albert Einstein fue famoso principalmente por ser...',
     'Pintor', 'Científico', 'Músico', 'Explorador', 'B', 'EASY', TRUE),
    ('HISTORIA', '¿Qué muro, que dividía una ciudad en dos, cayó en 1989?',
     'El Muro de Adriano', 'El Muro de Berlín', 'La Gran Muralla', 'El Muro de las Lamentaciones', 'B', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Quién lideró el movimiento de independencia de la India mediante la resistencia pacífica?',
     'Nelson Mandela', 'Mahatma Gandhi', 'Winston Churchill', 'Jawaharlal Nehru', 'B', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Qué antigua civilización construyó la ciudadela de Machu Picchu?',
     'Los aztecas', 'Los mayas', 'Los incas', 'Los olmecas', 'C', 'MEDIUM', TRUE),
    ('HISTORIA', '¿En qué siglo comenzó la Revolución Industrial?',
     'Siglo XVI', 'Siglo XVII', 'Siglo XVIII', 'Siglo XIX', 'C', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Cuántos días tiene un año común?',
     '360', '365', '364', '366', 'B', 'EASY', TRUE),
    ('CULTURA GENERAL', '¿Cuántas letras tiene el abecedario en español?',
     '26', '28', '27', '25', 'C', 'EASY', TRUE),
    ('CULTURA GENERAL', '¿Qué color resulta de mezclar azul y amarillo?',
     'Morado', 'Verde', 'Naranja', 'Gris', 'B', 'EASY', TRUE),
    ('CULTURA GENERAL', '¿Cuántos meses tiene un año?',
     '10', '11', '13', '12', 'D', 'EASY', TRUE),
    ('CULTURA GENERAL', '¿Cuál es considerado el libro más vendido de la historia?',
     'El Quijote', 'La Biblia', 'El principito', 'Harry Potter', 'B', 'EASY', TRUE),
    ('CULTURA GENERAL', '¿Qué idioma tiene más hablantes nativos en el mundo?',
     'Inglés', 'Español', 'Chino mandarín', 'Hindi', 'C', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Qué instrumento musical tiene 88 teclas?',
     'La guitarra', 'El violín', 'El piano', 'El arpa', 'C', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Cómo se llama el evento deportivo internacional que se celebra cada 4 años con muchos deportes distintos?',
     'El Mundial', 'Los Juegos Olímpicos', 'La Copa América', 'La Champions League', 'B', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Qué significan las siglas UNESCO?',
     'Unión de Naciones para la Salud', 'Organización de las Naciones Unidas para la Educación, la Ciencia y la Cultura', 'Unión Europea de Cultura', 'Organización Mundial de Comercio', 'B', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Cuál es el país más grande del mundo por territorio?',
     'China', 'Canadá', 'Rusia', 'Estados Unidos', 'C', 'EASY', TRUE),
    ('GEOGRAFÍA', '¿Cuál es el desierto más grande del mundo?',
     'El Sahara', 'El Gobi', 'El Atacama', 'El Kalahari', 'A', 'EASY', TRUE),
    ('GEOGRAFÍA', '¿En qué continente se encuentra Egipto?',
     'Asia', 'Europa', 'África', 'Oceanía', 'C', 'EASY', TRUE),
    ('GEOGRAFÍA', '¿Cuál es el lago más grande del mundo (también considerado un mar)?',
     'Lago Titicaca', 'Lago Victoria', 'El mar Caspio', 'Lago Superior', 'C', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Qué país europeo tiene una forma parecida a una bota en el mapa?',
     'España', 'Grecia', 'Italia', 'Portugal', 'C', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Qué país centroamericano es conocido como "la tierra de lagos y volcanes"?',
     'Costa Rica', 'El Salvador', 'Panamá', 'Honduras', 'B', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Qué estrecho separa Europa de África?',
     'El Estrecho de Bering', 'El Estrecho de Gibraltar', 'El Canal de la Mancha', 'El Estrecho de Magallanes', 'B', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Cuál es el animal terrestre más grande del mundo?',
     'El rinoceronte', 'El elefante', 'El hipopótamo', 'La jirafa', 'B', 'EASY', TRUE),
    ('ANIMALES', '¿A qué animal se le conoce como "el rey de la selva"?',
     'El tigre', 'El león', 'El leopardo', 'El oso', 'B', 'EASY', TRUE),
    ('ANIMALES', '¿Qué ave, aunque no puede volar, es la más grande del mundo?',
     'El pingüino', 'El avestruz', 'El pavo real', 'El pelícano', 'B', 'EASY', TRUE),
    ('ANIMALES', '¿Qué animal es capaz de cambiar de color para camuflarse?',
     'La iguana', 'El camaleón', 'La salamandra', 'El lagarto', 'B', 'EASY', TRUE),
    ('ANIMALES', '¿Cuál es el mamífero más grande del mundo?',
     'El elefante africano', 'La ballena azul', 'El rinoceronte', 'La jirafa', 'B', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Cuál es el animal terrestre más rápido del mundo?',
     'El caballo', 'El león', 'El guepardo', 'El antílope', 'C', 'MEDIUM', TRUE),
    ('ANIMALES', '¿En qué parte de su cuerpo transportan los canguros a sus crías?',
     'En la espalda', 'En la boca', 'En una bolsa marsupial', 'En las patas', 'C', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Cómo se le llama a un animal que puede vivir tanto en el agua como en tierra, como la rana?',
     'Reptil', 'Anfibio', 'Mamífero', 'Insecto', 'B', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Qué animal tiene el cuello más largo del mundo?',
     'El avestruz', 'El camello', 'La jirafa', 'El caballo', 'C', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué tecnología usamos para conectarnos a internet sin cables?',
     'Bluetooth', 'Wi-Fi', 'USB', 'Radio', 'B', 'EASY', TRUE),
    ('TECNOLOGÍA', '¿Cómo se llama el aparato que usamos para tomar fotografías?',
     'El escáner', 'La cámara', 'La impresora', 'El proyector', 'B', 'EASY', TRUE),
    ('TECNOLOGÍA', '¿Qué empresa creó el teléfono iPhone?',
     'Samsung', 'Google', 'Apple', 'Sony', 'C', 'EASY', TRUE),
    ('TECNOLOGÍA', '¿Cómo se llama la red mundial que conecta computadoras entre sí?',
     'Intranet', 'Internet', 'Bluetooth', 'Wi-Fi', 'B', 'EASY', TRUE),
    ('TECNOLOGÍA', '¿Qué dispositivo usamos principalmente para escribir en la computadora?',
     'El mouse', 'La pantalla', 'El teclado', 'Los parlantes', 'C', 'EASY', TRUE),
    ('TECNOLOGÍA', '¿Qué significan las siglas "PC"?',
     'Computadora Personal', 'Programa de Computación', 'Proceso Central', 'Panel de Control', 'A', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué empresa creó el sistema operativo Windows?',
     'Apple', 'Microsoft', 'IBM', 'Google', 'B', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Cómo se le llama al componente que actúa como el "cerebro" de la computadora?',
     'La RAM', 'El disco duro', 'El CPU (procesador)', 'La tarjeta gráfica', 'C', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué red social se hizo popular por compartir videos cortos con música?',
     'Facebook', 'TikTok', 'LinkedIn', 'Pinterest', 'B', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué significan las siglas "IA"?',
     'Internet Avanzado', 'Inteligencia Artificial', 'Información Automática', 'Interfaz de Aplicación', 'B', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Qué pez naranja se pierde en el océano y su papá sale a buscarlo?',
     'Nemo', 'Dory', 'Marlin', 'Bruce', 'A', 'EASY', TRUE),
    ('PELÍCULAS', '¿Cómo se llama el ogro verde protagonista de su propia película?',
     'Shrek', 'Hulk', 'El Grinch', 'Yoda', 'A', 'EASY', TRUE),
    ('PELÍCULAS', '¿Qué auto de carreras rojo es el protagonista de la película "Cars"?',
     'Mate', 'Rayo McQueen', 'Sally', 'Doc Hudson', 'B', 'EASY', TRUE),
    ('PELÍCULAS', '¿En qué película un abuelito viaja con su casa amarrada a globos?',
     'Up: Una aventura de altura', 'Wall-E', 'Coco', 'Intensa-Mente', 'A', 'EASY', TRUE),
    ('PELÍCULAS', '¿En qué película un niño viaja a la Tierra de los Muertos para conocer a sus antepasados?',
     'Coco', 'Moana', 'Encanto', 'El libro de la vida', 'A', 'EASY', TRUE),
    ('PELÍCULAS', '¿Cómo se llama la princesa polinesia que navega para salvar su isla?',
     'Pocahontas', 'Moana (Vaiana)', 'Mulán', 'Jasmine', 'B', 'EASY', TRUE),
    ('PELÍCULAS', '¿Qué familia tiene poderes mágicos en la película "Encanto"?',
     'Los Increíbles', 'La familia Madrigal', 'La familia Robinson', 'Los Parr', 'B', 'EASY', TRUE),
    ('PELÍCULAS', '¿Cómo se llama el panda que sueña con ser un guerrero Kung Fu?',
     'Po', 'Shifu', 'Tigresa', 'Mono', 'A', 'EASY', TRUE),
    ('PELÍCULAS', '¿En qué película unos animales de zoológico terminan perdidos en la selva de Madagascar?',
     'El Rey León', 'Madagascar', 'Río', 'Zootopia', 'B', 'EASY', TRUE),
    ('PELÍCULAS', '¿Cómo se llama la familia de superhéroes en "Los Increíbles"?',
     'Los Parr', 'Los Madrigal', 'Los Robinson', 'Los Bell', 'A', 'EASY', TRUE),
    ('PELÍCULAS', '¿Qué monstruo azul y peludo es el mejor amigo de Mike Wazowski en "Monsters, Inc."?',
     'Sulley', 'Randall', 'Boo', 'Celia', 'A', 'EASY', TRUE),
    ('PELÍCULAS', '¿Cómo se llama la joven que se enamora de un príncipe convertido en bestia?',
     'Bella', 'Aurora', 'Ariel', 'Jasmine', 'A', 'EASY', TRUE),
    ('PELÍCULAS', '¿Qué personaje encuentra una lámpara mágica con un genio adentro?',
     'Aladdín', 'Simba', 'Peter Pan', 'Hércules', 'A', 'EASY', TRUE),
    ('PELÍCULAS', '¿Cómo se llama la princesa que tiene el cabello mágico muy largo?',
     'Rapunzel', 'Elsa', 'Bella', 'Ariel', 'A', 'EASY', TRUE),
    ('PELÍCULAS', '¿Cómo se llama el niño que es criado en la selva por lobos y el oso Baloo?',
     'Tarzán', 'Mowgli', 'Peter Pan', 'Simba', 'B', 'EASY', TRUE),
    ('PELÍCULAS', '¿Cómo se llama el robot que limpia la Tierra y se enamora de otra robot llamada EVE?',
     'Wall-E', 'Baymax', 'R2-D2', 'Bumblebee', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Qué personaje de Pixar es un ratón chef que cocina en un restaurante de París?',
     'Remy', 'Mickey', 'Jerry', 'Stuart Little', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Cuál de estas NO es una de las emociones principales de la película "Intensa-Mente"?',
     'Alegría', 'Tristeza', 'Furia', 'Valentía', 'D', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Cómo se llama la ciudad de animales donde una zorra y una coneja policía resuelven un misterio?',
     'Zootopia', 'Ciudad Zoológica', 'Animalia', 'Fauna City', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Cómo se llama el pez de memoria a corto plazo que ayuda a buscar a Nemo?',
     'Dory', 'Bruce', 'Gill', 'Bloat', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Qué villano usa un guante para "chasquear" y desaparecer a la mitad del universo?',
     'Thanos', 'Darth Vader', 'Voldemort', 'Loki', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Cómo se llama el joven mago que estudia en el colegio Hogwarts?',
     'Harry Potter', 'Percy Jackson', 'Frodo', 'Peter Pan', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Qué criatura verde y gruñona vive en una cueva y odia la Navidad?',
     'El Grinch', 'Shrek', 'Hulk', 'Sulley', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Cómo se llama el droide dorado de "Star Wars" que habla muchos idiomas?',
     'R2-D2', 'C-3PO', 'BB-8', 'IG-11', 'B', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿En qué película un joven llamado Hipo se hace amigo de un dragón llamado Chimuelo?',
     'Cómo entrenar a tu dragón', 'El Rey León', 'Shrek', 'Mulán', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Cómo se llama el tiburón amistoso que intenta no comer peces en "Buscando a Nemo"?',
     'Bruce', 'Jaws', 'Gill', 'Nemo', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Qué superhéroe usa un traje de armadura y en realidad es Tony Stark?',
     'Iron Man', 'Batman', 'Thor', 'Capitán América', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Cómo se llama el pequeño robot médico inflable de la película "Big Hero 6"?',
     'Baymax', 'Wall-E', 'Bumblebee', 'EVE', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿En qué película un pez payaso llamado Marlin cruza el océano para encontrar a su hijo?',
     'Buscando a Nemo', 'La Sirenita', 'Río', 'Shark Tale', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Cómo se llama el pequeño extraterrestre azul y travieso adoptado por una niña hawaiana en "Lilo & Stitch"?',
     'Stitch', 'Scrump', 'Jumba', 'Pleakley', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Qué estudio de animación creó "Toy Story", la primera película totalmente animada por computadora?',
     'DreamWorks', 'Pixar', 'Illumination', 'Blue Sky Studios', 'B', 'HARD', TRUE),
    ('PELÍCULAS', '¿En qué año se estrenó la primera película de "Toy Story"?',
     '1995', '1998', '2001', '1990', 'A', 'HARD', TRUE),
    ('PELÍCULAS', '¿Cómo se llama el reino ficticio donde se desarrolla la historia de "Frozen"?',
     'Agrabah', 'Arendelle', 'Genovia', 'Corona', 'B', 'HARD', TRUE),
    ('PELÍCULAS', '¿Qué villana quiere robar los cachorros dálmatas en "101 Dálmatas"?',
     'Úrsula', 'Cruella de Vil', 'Maléfica', 'Madre Gothel', 'B', 'HARD', TRUE),
    ('PELÍCULAS', '¿Cómo se llama el reino donde vive Rapunzel en "Enredados"?',
     'Corona', 'Arendelle', 'Agrabah', 'Camelot', 'A', 'HARD', TRUE),
    ('FÚTBOL', '¿Qué selección ganó el Mundial de Fútbol de 2006?',
     'Italia', 'Francia', 'Alemania', 'Brasil', 'A', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué club ganó la Champions League en 2022?',
     'Liverpool', 'Real Madrid', 'Manchester City', 'Chelsea', 'B', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Cómo se llama el premio al mejor jugador de fútbol del mundo?',
     'La Bota de Oro', 'El Guante de Oro', 'El Balón de Oro', 'El Premio Puskás', 'C', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué selección ganó la Eurocopa de 2008?',
     'Alemania', 'Italia', 'Rusia', 'España', 'D', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué selección de fútbol es apodada "la Canarinha"?',
     'Brasil', 'Argentina', 'México', 'Colombia', 'A', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿En qué estadio se jugó la final del Mundial de Fútbol de 2022?',
     'Maracaná', 'Lusail', 'Camp Nou', 'Wembley', 'B', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué club italiano es conocido como "la Vecchia Signora"?',
     'El Milan', 'El Inter', 'La Juventus', 'La Roma', 'C', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué club español ha ganado más Ligas de España (hasta 2023)?',
     'El Barcelona', 'El Atlético', 'El Sevilla', 'El Real Madrid', 'D', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Cuántos Mundiales de fútbol ha ganado Uruguay?',
     '2', '1', '3', '4', 'A', 'MEDIUM', TRUE),
    ('FÚTBOL', '¿Qué jugador francés fue clave en el Mundial de 2018 con solo 19 años?',
     'Antoine Griezmann', 'Kylian Mbappé', 'Paul Pogba', 'Karim Benzema', 'B', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuánto es 11 × 11?',
     '111', '100', '121', '122', 'C', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuál es el perímetro de un cuadrado cuyo lado mide 7?',
     '14', '21', '49', '28', 'D', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuánto es 2/4 + 1/4?',
     '3/4', '3/8', '1/4', '4/4', 'A', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuántos minutos hay en tres horas y media?',
     '180', '210', '190', '350', 'B', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuál es el doble de 125?',
     '225', '275', '250', '1250', 'C', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', 'Si ahorras 10 monedas cada día, ¿cuántas tienes en 30 días?',
     '40', '3000', '130', '300', 'D', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuánto es 99 + 1 − 50?',
     '50', '150', '49', '51', 'A', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Qué número multiplicado por 6 da 42?',
     '6', '7', '8', '36', 'B', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuál es la mitad de 340?',
     '160', '180', '170', '320', 'C', 'MEDIUM', TRUE),
    ('MATEMÁTICAS', '¿Cuántos centímetros hay en 2 metros?',
     '20', '2000', '2', '200', 'D', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Qué planeta es el más alejado del Sol?',
     'Neptuno', 'Urano', 'Saturno', 'Plutón', 'A', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Qué parte del ojo le da el color?',
     'La pupila', 'El iris', 'El cristalino', 'La retina', 'B', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Qué metal conduce mejor la electricidad?',
     'El hierro', 'El aluminio', 'El cobre', 'El plomo', 'C', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Qué instrumento se usa para observar el espacio?',
     'El microscopio', 'El termómetro', 'El barómetro', 'El telescopio', 'D', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Cuántos sentidos reconocemos tradicionalmente en las personas?',
     '5', '4', '6', '7', 'A', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Qué gas exhalamos al respirar?',
     'Oxígeno', 'Dióxido de carbono', 'Nitrógeno', 'Hidrógeno', 'B', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Cómo se llama el proceso por el que las plantas pierden agua por sus hojas?',
     'Fotosíntesis', 'Respiración', 'Transpiración', 'Germinación', 'C', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Qué mamífero marino es famoso por su gran inteligencia?',
     'La foca', 'La morsa', 'El manatí', 'El delfín', 'D', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Qué capa de la atmósfera nos protege de los rayos ultravioleta?',
     'La capa de ozono', 'La troposfera', 'La exosfera', 'La ionosfera', 'A', 'MEDIUM', TRUE),
    ('CIENCIA', '¿Cuántos dientes de leche tiene, aproximadamente, un niño pequeño?',
     '10', '20', '24', '32', 'B', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Qué volcán sepultó la ciudad romana de Pompeya?',
     'El Etna', 'El Fuji', 'El Vesubio', 'El Krakatoa', 'C', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Qué imperio gobernaba en México cuando llegaron los españoles?',
     'El maya', 'El inca', 'El olmeca', 'El mexica (azteca)', 'D', 'MEDIUM', TRUE),
    ('HISTORIA', '¿En qué país se encuentra la antigua ciudad de Petra, tallada en roca?',
     'Jordania', 'Egipto', 'Grecia', 'Turquía', 'A', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Cómo se llamó la larga guerra entre Francia e Inglaterra en la Edad Media?',
     'La Guerra de las Rosas', 'La Guerra de los Cien Años', 'La Guerra de los Treinta Años', 'La Guerra de Troya', 'B', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Qué reina británica gobernó durante 70 años y murió en 2022?',
     'Victoria', 'Isabel I', 'Isabel II', 'Ana I', 'C', 'MEDIUM', TRUE),
    ('HISTORIA', '¿En qué año llegó el ser humano a la Luna?',
     '1959', '1975', '1981', '1969', 'D', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Qué cultura prehispánica dibujó las famosas líneas de Nazca?',
     'La cultura nazca', 'La cultura inca', 'La cultura maya', 'La cultura tolteca', 'A', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Qué rey fue coronado emperador en Roma en el año 800?',
     'Napoleón', 'Carlomagno', 'Carlos V', 'Justiniano', 'B', 'MEDIUM', TRUE),
    ('HISTORIA', '¿En qué año comenzó la Revolución Francesa?',
     '1776', '1815', '1789', '1799', 'C', 'MEDIUM', TRUE),
    ('HISTORIA', '¿Qué barco llevó a los primeros colonos ingleses a América en 1620?',
     'El Beagle', 'La Santa María', 'El Endurance', 'El Mayflower', 'D', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Cuántos dientes tiene un adulto sin contar las muelas del juicio?',
     '28', '20', '24', '32', 'A', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Cuál es la capital de Suiza?',
     'Ginebra', 'Berna', 'Zúrich', 'Basilea', 'B', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Cuántas patas tiene, por lo general, una estrella de mar?',
     '4', '6', '5', '8', 'C', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Cuántos minutos son una hora y media?',
     '60', '120', '150', '90', 'D', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Qué monumento de mármol blanco está en la India?',
     'El Taj Mahal', 'La Gran Muralla', 'El Coliseo', 'La Alhambra', 'A', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Cuántos lados tiene un octágono?',
     '6', '8', '7', '10', 'B', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Qué comida típica de México se prepara con tortilla y relleno?',
     'La paella', 'La arepa', 'El taco', 'El sushi', 'C', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Qué famosa torre inclinada se encuentra en Italia?',
     'La Torre Eiffel', 'El Big Ben', 'La Torre CN', 'La de Pisa', 'D', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Cuántas semanas tiene, aproximadamente, un año?',
     '52', '48', '50', '56', 'A', 'MEDIUM', TRUE),
    ('CULTURA GENERAL', '¿Qué país organizó los Juegos Olímpicos de 2024?',
     'Japón', 'Francia', 'Brasil', 'Inglaterra', 'B', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Cuál es la capital de Colombia?',
     'Medellín', 'Cali', 'Bogotá', 'Cartagena', 'C', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Qué pequeño país está entre España y Francia?',
     'Mónaco', 'Luxemburgo', 'San Marino', 'Andorra', 'D', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Cuál es el país más largo del mundo, de norte a sur?',
     'Chile', 'Argentina', 'Brasil', 'México', 'A', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Qué río atraviesa la ciudad de Londres?',
     'El Sena', 'El Támesis', 'El Rin', 'El Danubio', 'B', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Cuál es la capital de Grecia?',
     'Roma', 'Salónica', 'Atenas', 'Estambul', 'C', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Cuál es la capital de Egipto?',
     'Alejandría', 'Luxor', 'Aswán', 'El Cairo', 'D', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Qué cordillera recorre la costa oeste de América del Sur?',
     'Los Andes', 'Los Alpes', 'Los Urales', 'Las Rocosas', 'A', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Cuál es la capital de Islandia?',
     'Oslo', 'Reikiavik', 'Copenhague', 'Helsinki', 'B', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Qué desierto se extiende por el suroeste de Estados Unidos y el norte de México?',
     'El de Atacama', 'El Gobi', 'El de Sonora', 'El de Namib', 'C', 'MEDIUM', TRUE),
    ('GEOGRAFÍA', '¿Cuál es la capital de Nueva Zelanda?',
     'Auckland', 'Sídney', 'Melbourne', 'Wellington', 'D', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Qué ave aparece en el escudo de la bandera de México?',
     'El águila real', 'El colibrí', 'El quetzal', 'El cóndor', 'A', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Cómo se llama la cría de la vaca?',
     'El potro', 'El ternero', 'El cordero', 'El cabrito', 'B', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Qué marsupial australiano duerme casi todo el día?',
     'El canguro', 'El demonio de Tasmania', 'El koala', 'El wombat', 'C', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Cómo se llama el sonido que hace el perro?',
     'El maullido', 'El mugido', 'El cacareo', 'El ladrido', 'D', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Qué pez de colores vive en el arrecife y protagoniza "Buscando a Nemo"?',
     'El pez payaso', 'El pez globo', 'La sardina', 'El tiburón martillo', 'A', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Qué gran felino aparece como el tigre Shere Khan en "El libro de la selva"?',
     'El león', 'El tigre', 'El leopardo', 'El puma', 'B', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Cómo se llama la hembra del caballo?',
     'La vaca', 'La burra', 'La yegua', 'La oveja', 'C', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Qué animal construye presas y diques en los ríos?',
     'La nutria', 'El mapache', 'El oso', 'El castor', 'D', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Qué anfibio croa en los estanques?',
     'La rana', 'La lagartija', 'La salamandra sin cola', 'El grillo', 'A', 'MEDIUM', TRUE),
    ('ANIMALES', '¿Qué ave puede imitar palabras y sonidos humanos?',
     'El canario', 'El loro', 'El gorrión', 'La paloma', 'B', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué botón del ratón abre el menú con opciones en la mayoría de computadoras?',
     'El izquierdo', 'La rueda', 'El derecho', 'El de encendido', 'C', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué significa "online"?',
     'Apagado', 'Descargando', 'Imprimiendo', 'Conectado o en línea', 'D', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué tipo de pantalla usan casi todos los celulares actuales?',
     'Táctil', 'De tubo', 'De tinta', 'De proyección', 'A', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Cómo se llama el cable que conecta la computadora al internet?',
     'Cable HDMI', 'Cable de red (Ethernet)', 'Cable de audio', 'Cable VGA', 'B', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué empresa creó el buscador Bing?',
     'Google', 'Apple', 'Microsoft', 'Amazon', 'C', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué significa la palabra "link" en una página web?',
     'Imagen', 'Botón', 'Búsqueda', 'Enlace', 'D', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué se guarda cuando enviamos archivos a la "papelera" de la computadora?',
     'Archivos que se borraron', 'Archivos nuevos', 'Virus', 'Contraseñas', 'A', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué dispositivo usas para escuchar audio sin que los demás lo oigan?',
     'La bocina', 'Los audífonos', 'El micrófono', 'El altavoz', 'B', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Cómo se llama el servicio de almacenamiento en la nube de Google?',
     'iCloud', 'OneDrive', 'Google Drive', 'Dropbox', 'C', 'MEDIUM', TRUE),
    ('TECNOLOGÍA', '¿Qué hace la tecla Enter (Intro) del teclado?',
     'Borrar texto', 'Subir volumen', 'Apagar la pantalla', 'Confirmar o ejecutar', 'D', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Qué película de Pixar trata sobre un anciano que ata su casa a muchos globos?',
     'Up: una aventura de altura', 'Ratatouille', 'Cars', 'Valiente', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿En qué película de Disney aparece el extraterrestre Stitch?',
     'Buzz Lightyear', 'Lilo & Stitch', 'Coco', 'Moana', 'B', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿En qué ciudad transcurre la película "Ratatouille"?',
     'Londres', 'Roma', 'París', 'Nueva York', 'C', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Qué película de Disney cuenta la historia de Miguel y la Tierra de los Muertos?',
     'Encanto', 'Soul', 'Luca', 'Coco', 'D', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿En qué película de Disney aparece el robot enfermero Baymax?',
     'Big Hero 6', 'WALL·E', 'Robots', 'Metrópolis', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿En qué ciudad animal transcurre la película "Zootopia"?',
     'Agrabah', 'Zootrópolis', 'Arendelle', 'Atlántica', 'B', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Qué villana de "101 Dálmatas" quiere hacer abrigos con los perritos?',
     'Úrsula', 'Maléfica', 'Cruella de Vil', 'La Reina Malvada', 'C', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿En qué película de Disney aparece el muñeco de nieve Olaf?',
     'Encanto', 'Valiente', 'La Sirenita', 'Frozen', 'D', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿Qué película de Disney cuenta la historia del héroe griego Hércules?',
     'Hércules', 'Heracles', 'Aquiles', 'Zeus', 'A', 'MEDIUM', TRUE),
    ('PELÍCULAS', '¿En qué película animada aparece el dragón llamado "Furia Nocturna"?',
     'El dragón de Pete', 'Cómo entrenar a tu dragón', 'Mulán', 'Shrek', 'B', 'MEDIUM', TRUE);
